language: node_js
node_js:
  - lts/*
install:
  - npm i # npm ci
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  github_token: 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 # 在 GitHub 中生成，用于允许 Travis 向你的仓库推送代码。在 Travis 的项目设置页面进行配置，设置为 secure variable
  keep_history: true
  on:
    branch: master
